### ISSUE TITLE
have a changelog file

### ISSUE THREAD

**Issue by seiyria** [seiyria/anamnesiac#7]
changelog file should be a yml:

```yml

- date: 2018-12-15
  charactersAdditions:
	- name: 2B
      notes: 2B was added as a rank 10/10
  characterChanges: 
	- name: A2
	  notes: A2 was moved to rank 9/10
  itemAdditions:
	- name: Beastlord
	  notes: It was added.
  itemChanges:
	- name: Divine Wave Gun
	  notes: MLB factor is 5, not 4

```
